version: '2'
services:
  mongo:
    image: mongo
    volumes:
      - "/var/abx/mongodb:/data/db"
    ports:
      - "27017:27017"

  rabbit:
    image: byteflair/rabbitmq-stomp
    ports:
        - "15672:15672"
        - "5672:5672"
        - "15674:15674"
        - "61613:61613"
    environment:
        RABBITMQ_ERLANG_COOKIE: abx-01
        RABBITMQ_DEFAULT_USER: abx-admin
        RABBITMQ_DEFAULT_PASS: abx01

  01-notifier:
    build: ../ecosystem/01.notifier/
    ports:
      - "8081:80"
    depends_on:
      - rabbit
    entrypoint: ./wait-for-it.sh rabbit:5672 -- npm start
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb://mongo/techzone-db
      RABBITMQ_HOST: rabbit
      RABBITMQ_USER: abx-admin
      RABBITMQ_PASSWORD: abx01
    links:
      - mongo
      - rabbit
